library("tidyr")
library("reshape2")
library("plyr")
disease<-read.csv("/disease_combined.csv",header=TRUE)
disease.columns<-colnames(disease)
disease.columns
disease.columns<-disease.columns[1:132]
disease.columns
disease.melt<-melt(disease,id.vars=c("prognosis","patientID"),variable.name="Symptom",value.name="Presence")
head(disease.melt)
write.csv(disease.melt,"/disease_combined_melt2.csv")